version: '1.0'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - interalnet

  
  blecommerce:
    build: .
    image: bl-e-commerce:1.0
    restart: unless-stopped
    ports:
    - ${SERVER_PORT}:${CONTAINER_PORT}
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - interalnet

networks:
  interalnet:
    driver: bridge